#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# plugins
## swallow
pgrep bspswallow || "$(pwd)/plugins/bspswallow/bspswallow" &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 0
bspc config window_gap 12

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Screenkey manage=off

# playwright browsers
bspc rule -a firefox-default state=floating
bspc rule -a Chromium-browser state=floating

"$HOME/.config/polybar/launch.sh"
